language: python

python:
    - 2.7
    - 2.6
    - 3.2
    - 3.3
env:
    - NUMPY_VERSION=1.7.0

before_install:
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq
   - sudo apt-get install -qq python-numpy python-scipy cython libatlas-dev liblapack-dev gfortran
install:
   - export PYTHONIOENCODING=UTF8 # just in case
   - pip install --upgrade "numpy==$NUMPY_VERSION" --use-mirrors
   - pip install python-dateutil --use-mirrors
   - pip install pytz --use-mirrors
   - pip install http://mpia.de/~robitaille/python/matplotlib-1.2.0_fixed.tar.gz
   - pip install Cython --use-mirrors
   - pip install astropy --use-mirrors
script: python setup.py test
