language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds
addons:
    apt:
        packages:
            - graphviz

python:
    - 2.7
    - 3.5
    - 3.6

env:
    global:
        - ASTROPY_VERSION=2.0
        - NUMPY_VERSION=1.13
        - MATPLOTLIB_VERSION=2.0
        - SETUP_XVFB=True
        - CONDA_DEPENDENCIES='nose pyqt matplotlib pillow scikit-image reproject>=0.4 pytest-mpl pyregion'
        - CONDA_CHANNELS='astropy-ci-extras astropy'
        - SETUP_CMD='test --remote-data --coverage'

    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'

        # Try Astropy development and LTS version
        - python: 3.6
          env: ASTROPY_VERSION=development
        - python: 2.7
          env: ASTROPY_VERSION=lts
        - python: 3.6
          env: ASTROPY_VERSION=lts

        # Try older numpy version
        - python: 2.7
          env: NUMPY_VERSION=1.11 MATPLOTLIB_VERSION=1.5
               CONDA_DEPENDENCIES='nose pyqt=4 matplotlib pillow scikit-image reproject>=0.4'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - python setup.py $SETUP_CMD

after_success:
    # Uncomment line below if coveralls.io is set up for this package.
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls; fi
